### ISSUE TITLE
Create a yaml file to store sector/instrument hierarchy and associated labels

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/cpr-issues#59]

**Comment by chrisaballard** [comment]
@marcusodavies has defined two spreadsheets in Google Sheets which define a two-tier hierarhical structure for Sectors and Instruments. Each of the lower tiers is mapped to a list of keywords that might be indicative that a passage is related to the sector/instrument. Each spreadsheet has been normalised so we have one row per top-tier, sub-tier and keyword.

To faciliate easier maintenance and loading of this structure, I will convert this structure to two yaml files. These will define a hirarchical format which can go beyond two levels if necessary in the future:

```yaml
levels:
  - name: AGRICULTURE, FORESTRY & OTHER LAND USE (AFOLU)
    levels:
      - name: Agriculture (general)
        keywords:
          - agricultural infrastructure
          - agricultural productivity
          - agriculture
          - agroforestry
          - agropastoral
          - agrosilvopastoral
          - aiochar
          - biomass
          - ...
      - name: Agricultural greenhouse gas emissions
        keywords:
          - agricultural carbon dioxide
          - agricultural greenhouse gas emissions
          - agricultural methane
          - agricultural nitrous oxide
          - ...
      - ...
  - ...
```
